package in.techseva.cb.api.metrics;

import in.techseva.cb.core.domain.CostRecord;
import in.techseva.cb.core.domain.Fix;
import in.techseva.cb.core.domain.Vulnerability;
import in.techseva.cb.core.events.EscalationEvent;
import in.techseva.cb.core.events.FixGeneratedEvent;
import in.techseva.cb.core.events.PRRaisedEvent;
import in.techseva.cb.core.events.VulnerabilityDetectedEvent;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.DistributionSummary;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import jakarta.annotation.PostConstruct;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;

/**
 * Registers and updates Micrometer custom metrics for Prometheus scraping.
 * Metric names follow Prometheus conventions (snake_case).
 */
@Service
public class CbMetricsService {

    private final MeterRegistry registry;

    // Counters
    private Counter vulnerabilitiesDetected;
    private Counter fixesGenerated;
    private Counter prsCreated;
    private Counter escalationsTriggered;

    // Cost metrics
    private DistributionSummary llmCostSummary;
    private Counter llmTokensTotal;

    // Per-model token counters cache
    private final ConcurrentHashMap<String, Counter> tokenCountersByModel = new ConcurrentHashMap<>();

    // Pipeline latency timers (stored per vulnerability for start-time tracking)
    private final ConcurrentHashMap<String, Long> pipelineStartTimes = new ConcurrentHashMap<>();

    public CbMetricsService(MeterRegistry registry) {
        this.registry = registry;
    }

    @PostConstruct
    public void registerMetrics() {
        vulnerabilitiesDetected = Counter.builder("cb_vulnerabilities_detected_total")
                .description("Total number of vulnerabilities detected by SonarQube scanner")
                .register(registry);

        fixesGenerated = Counter.builder("cb_fixes_generated_total")
                .description("Total number of fixes generated by the LangGraph agent")
                .register(registry);

        prsCreated = Counter.builder("cb_prs_created_total")
                .description("Total number of pull requests created")
                .register(registry);

        escalationsTriggered = Counter.builder("cb_escalations_triggered_total")
                .description("Total number of escalations triggered after max retries")
                .register(registry);

        llmCostSummary = DistributionSummary.builder("cb_llm_cost_dollars")
                .description("LLM API cost per fix in USD")
                .baseUnit("dollars")
                .register(registry);

        llmTokensTotal = Counter.builder("cb_llm_tokens_total")
                .description("Total LLM tokens consumed (input + output)")
                .register(registry);
    }

    @EventListener
    public void onVulnerabilityDetected(VulnerabilityDetectedEvent event) {
        vulnerabilitiesDetected.increment();
        pipelineStartTimes.put(event.getVulnerability().id(), System.currentTimeMillis());
        registry.counter("cb_vulnerability_by_severity_total",
                "severity", event.getVulnerability().severity() != null
                        ? event.getVulnerability().severity().name() : "UNKNOWN",
                "cwe", event.getVulnerability().cweId() != null ? event.getVulnerability().cweId() : "UNKNOWN"
        ).increment();
    }

    @EventListener
    public void onFixGenerated(FixGeneratedEvent event) {
        fixesGenerated.increment();
        Fix fix = event.getFix();
        registry.counter("cb_fix_by_model_total",
                "model", fix.llmModel() != null ? fix.llmModel() : "unknown"
        ).increment();
    }

    @EventListener
    public void onPRRaised(PRRaisedEvent event) {
        prsCreated.increment();
        Long startMs = pipelineStartTimes.remove(event.getVulnerability().id());
        if (startMs != null) {
            long durationMs = System.currentTimeMillis() - startMs;
            Timer.builder("cb_pipeline_duration_seconds")
                    .description("End-to-end pipeline duration from detection to PR")
                    .register(registry)
                    .record(durationMs, TimeUnit.MILLISECONDS);
        }
        Fix fix = event.getFix();
        registry.gauge("cb_fix_confidence", fix.confidence());
    }

    @EventListener
    public void onEscalation(EscalationEvent event) {
        escalationsTriggered.increment();
        pipelineStartTimes.remove(event.getVulnerability().id());
        registry.counter("cb_escalation_by_retry_count_total",
                "retryCount", String.valueOf(event.getVulnerability().retryCount())
        ).increment();
    }

    public void recordCost(CostRecord record) {
        llmCostSummary.record(record.costUsd());
        long totalTokens = record.inputTokens() + record.outputTokens();
        llmTokensTotal.increment(totalTokens);

        tokenCountersByModel.computeIfAbsent(record.llmModel(),
            model -> Counter.builder("cb_llm_tokens_by_model_total")
                    .tag("model", model)
                    .description("Total tokens consumed per LLM model")
                    .register(registry)
        ).increment(totalTokens);

        registry.summary("cb_llm_cost_by_model_dollars",
                "model", record.llmModel() != null ? record.llmModel() : "unknown"
        ).record(record.costUsd());
    }
}
