apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cb-ingress-api
  namespace: cb-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - host: compliance-buddy.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cb-api
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cb-ingress-docs
  namespace: cb-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: compliance-buddy.local
      http:
        paths:
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: cb-api
                port:
                  number: 8080
          - path: /v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: cb-api
                port:
                  number: 8080
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: cb-api
                port:
                  number: 8080
          - path: /sonar
            pathType: Prefix
            backend:
              service:
                name: cb-sonarqube
                port:
                  number: 9000
          - path: /api/v1/scanner
            pathType: Prefix
            backend:
              service:
                name: cb-scanner
                port:
                  number: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cb-ingress-monitoring
  namespace: cb-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: compliance-buddy.local
      http:
        paths:
          - path: /grafana(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana
                port:
                  number: 3000
          - path: /prometheus(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
