apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cb-system

resources:
  # Namespace
  - namespace.yaml
  # Config / Secrets
  - configmap.yaml
  - secrets.yaml
  # Infrastructure
  - mongodb.yaml
  - qdrant.yaml
  - kafka.yaml
  - redis.yaml
  - elasticsearch.yaml
  - opa.yaml
  - ollama.yaml
  # Observability
  - tempo.yaml
  - loki.yaml
  - prometheus.yaml
  - grafana.yaml
  # SonarQube
  - sonarqube.yaml
  # CB Services
  - cb-python-embedder.yaml
  - cb-api.yaml
  - cb-services.yaml
  - cb-escalation.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: compliance-buddy
  app.kubernetes.io/managed-by: kustomize
