package in.techseva.cb.patcher.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Applies gradle dependency version patches generated by the AI agent.
 *
 * Input format (one patch per line):
 *   group:artifact:oldVersion -> newVersion
 *
 * Handles:
 *  - build.gradle (Groovy)      — 'group:artifact:version' and "group:artifact:version"
 *  - build.gradle.kts (Kotlin)  — "group:artifact:version"
 *  - gradle.properties          — version.key=oldVersion lines
 *
 * Walks the full repo tree so multi-module projects are fully patched.
 */
@Component
public class GradlePatcher {

    private static final Logger log = LoggerFactory.getLogger(GradlePatcher.class);

    // Matches: group:artifact:oldVersion -> newVersion
    private static final Pattern PATCH_LINE = Pattern.compile(
            "^([\\w.\\-]+):([\\w.\\-]+):([\\w.\\-]+)\\s*->\\s*([\\w.\\-]+)$");

    public void applyGradlePatch(String repoRoot, String gradlePatch) throws IOException {
        if (gradlePatch == null || gradlePatch.isBlank()) return;

        for (String raw : gradlePatch.split("\\n")) {
            String line = raw.strip();
            if (line.isEmpty() || line.startsWith("#")) continue;

            Matcher m = PATCH_LINE.matcher(line);
            if (!m.matches()) {
                log.warn("Unrecognized gradle patch line (expected 'g:a:oldVer -> newVer'): {}", line);
                continue;
            }

            String group    = m.group(1);
            String artifact = m.group(2);
            String oldVer   = m.group(3);
            String newVer   = m.group(4);

            log.info("Applying dep patch: {}:{}:{} -> {}", group, artifact, oldVer, newVer);
            patchRepo(Paths.get(repoRoot), group, artifact, oldVer, newVer);
        }
    }

    private void patchRepo(Path repoRoot, String group, String artifact,
                            String oldVer, String newVer) throws IOException {
        List<Path> targets = collectBuildFiles(repoRoot);
        int totalPatched = 0;

        for (Path file : targets) {
            int changed = patchFile(file, group, artifact, oldVer, newVer);
            totalPatched += changed;
        }

        if (totalPatched == 0) {
            log.warn("No occurrences of {}:{}:{} found in any build file under {}",
                    group, artifact, oldVer, repoRoot);
        } else {
            log.info("Patched {} occurrence(s) of {}:{}:{} -> {} across {} file(s)",
                    totalPatched, group, artifact, oldVer, newVer, targets.size());
        }
    }

    private int patchFile(Path file, String group, String artifact,
                           String oldVer, String newVer) throws IOException {
        String name = file.getFileName().toString();
        String content = Files.readString(file, StandardCharsets.UTF_8);
        String patched;

        if (name.equals("gradle.properties")) {
            patched = patchProperties(content, group, artifact, oldVer, newVer);
        } else {
            patched = patchGroovyOrKts(content, group, artifact, oldVer, newVer);
        }

        if (!patched.equals(content)) {
            Files.writeString(file, patched, StandardCharsets.UTF_8);
            log.debug("Patched {}", file);
            // Count replacements
            return countOccurrences(content, oldVer) - countOccurrences(patched, oldVer);
        }
        return 0;
    }

    /**
     * Patches Groovy/Kotlin build.gradle(.kts) files.
     * Replaces both quoted forms:
     *   'group:artifact:oldVersion'
     *   "group:artifact:oldVersion"
     */
    private String patchGroovyOrKts(String content, String group, String artifact,
                                     String oldVer, String newVer) {
        String oldCoord = group + ":" + artifact + ":" + oldVer;
        String newCoord = group + ":" + artifact + ":" + newVer;
        return content.replace(oldCoord, newCoord);
    }

    /**
     * Patches gradle.properties files.
     * Handles lines like:
     *   springVersion=5.3.27
     *   version.spring-web=5.3.27
     *   spring_web_version=5.3.27
     * by replacing any line whose value matches oldVer and whose key looks like
     * it could be a version variable for this artifact.
     */
    private String patchProperties(String content, String group, String artifact,
                                    String oldVer, String newVer) {
        String[] lines = content.split("\n", -1);
        StringBuilder sb = new StringBuilder();
        String artifactNorm = artifact.toLowerCase().replace('-', '.').replace('_', '.');

        for (String line : lines) {
            String trimmed = line.trim();
            if (!trimmed.startsWith("#") && trimmed.contains("=")) {
                int eq = trimmed.indexOf('=');
                String key = trimmed.substring(0, eq).trim().toLowerCase()
                        .replace('-', '.').replace('_', '.');
                String val = trimmed.substring(eq + 1).trim();

                if (val.equals(oldVer) && key.contains(artifactNorm.split("\\.")[0])) {
                    sb.append(line, 0, line.indexOf('=') + 1).append(newVer).append('\n');
                    log.debug("Patched gradle.properties key: {} = {} -> {}", key, oldVer, newVer);
                    continue;
                }
            }
            sb.append(line).append('\n');
        }

        // Remove trailing extra newline added by the split/join
        String result = sb.toString();
        if (!content.endsWith("\n") && result.endsWith("\n")) {
            result = result.substring(0, result.length() - 1);
        }
        return result;
    }

    private List<Path> collectBuildFiles(Path repoRoot) throws IOException {
        List<Path> files = new ArrayList<>();
        try (var walk = Files.walk(repoRoot)) {
            walk.filter(p -> {
                String name = p.getFileName().toString();
                // Skip generated/build output directories
                String pathStr = p.toString().replace('\\', '/');
                if (pathStr.contains("/build/") || pathStr.contains("/.gradle/")) return false;
                return name.equals("build.gradle")
                        || name.equals("build.gradle.kts")
                        || name.equals("gradle.properties");
            }).forEach(files::add);
        }
        log.debug("Found {} patchable Gradle files under {}", files.size(), repoRoot);
        return files;
    }

    private int countOccurrences(String text, String sub) {
        int count = 0, idx = 0;
        while ((idx = text.indexOf(sub, idx)) != -1) { count++; idx += sub.length(); }
        return count;
    }
}
